version: '3.1' 

services: 
  wordpress: 
    image: wordpress:latest 
    ports:
      - 8046:80 
    environment:
      WORDPRESS_DB_PASSWORD: redhat 
    volumes:
      - ./wordpress_data:/var/www/html

  mysql:
    image: mysql:latest
    environment:
       MYSQL_ROOT_PASSWORD: redhat 
    volumes:
      - ./mysql_data:/var/lib/mysql

